name: Java CI

on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - geary.iml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: set-nms-version
        run: echo ::set-output name=nms-version::1.15.1
      - name: Cache NMS
        id: cache-nms
        uses: actions/cache@v1
        with:
          path: nms-build/.m2/repository/
          key: ${{ runner.os }}-${{ steps.set-nms-version.outputs.nms-version }}-nms
      - name: Build NMS
        if: steps.cache-nms.outputs.cache-hit != 'true'
        uses: derongan/nmsaction@v1
        with:
          rev: ${{ steps.set-nms-version.outputs.nms-version }}
      - name: Install nms into m2
        run: mkdir -p $HOME/.m2/repository && cp -a nms-build/.m2/repository/* $HOME/.m2/repository
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew -PbuildNo=${{ github.run_number }} jar shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: package
          path: build/libs
